apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "windows"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://1.1.1.1/windowsvm.raw"
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
