apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "windows"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://10.8.120.188/Summit2019.raw"
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
