apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath000${counter}
  labels:
    type: local
spec:
  storageClassName: mon-sc
  capacity:
    storage: ${mon_size}Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mon"
