apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ${cluster}
spec:
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: mon-sc
      volumeMode: Filesystem
      resources:
        requests:
          storage: ${mon_size}Gi
  storageDeviceSets:
  - name: osd
    count: ${osd_count}
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: osd-sc
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: ${osd_size}Gi
    portable: false
