apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "rhel8-pvc"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://1.1.1.1/rhel8.qcow2"
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
